export default {
  experience: {
    title: 'Fishing with father and son',
  },
  offer: {
    image: 'https://picsum.photos/200/300',
    title: 'An unforgettable father-and-son fishing experience in Jura',
    hat: '1 Guest - Jun 07, 2019 - €200',
    status: 'Pending',
    mode: 'warning',
  },
  booking: {
    startDate: '28 Jun, 2019',
    endDate: '31 Jun, 2019',
    source: 'marketplace',
    experienceCover: 'https://picsum.photos/200/300',
    experienceTitle:
      'An unforgettable father-and-son fishing experience in Jura',
    experienceAddress: 'Rue Haute 4, 6990 Hotton, Belgique',
    guests: 3,
    duration: 2,
    conversationId: 'ada72f55-fdae-4ba8-ad80-b65c42458d49',
    customerFullName: 'Kevin Tassi',
    customerEmail: 'info@fishtripr.com',
    statusText: 'Accepted',
    statusType: 'success',
    totalPrice: 350,
    deposit: 0,
    currency: 'EUR',
    currencySymbol: '€',
  },
  dashboard: {
    yearRevenue: [
      { label: 'Jan', value: 200 },
      { label: 'Feb', value: 300 },
      { label: 'Mar', value: 0 },
      { label: 'Apr', value: 200 },
      { label: 'May', value: 500 },
      { label: 'Jun', value: 700 },
      { label: 'Jul', value: 400 },
      { label: 'Aug', value: 800 },
      { label: 'Sep', value: 400 },
      { label: 'Oct', value: 200 },
      { label: 'Nov', value: 0 },
      { label: 'Dec', value: 0 },
    ],
  },
  modal: {
    image: 'https://picsum.photos/200/300',
  },
}
